{
    "name": "HR Management Base",
    "category": "HR-Odex",
    "summary": "HR Management base config module for Employee Record",
    "version": "14.0",
    "sequence": 4,
    "website": "http://exp-sa.com",
    "license": "GPL-3",
    "author": "Expert Co. Ltd.",
    "depends": [
        "base",
        "hr",
        "hr_docs_expiry",
        "maintenance",
        "account",
        "hr_holidays_community",
        "hr_contract",
    ],
    "data": [
        "security/hr_base_security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence.xml",
        "data/ir_cron.xml",
        # "views/assets_document_view.xml",
        "views/hr_base_view.xml",
        "views/employee_iqama_renewal_view.xml",
        "views/hr_dependent_view.xml",
        "views/category_info_view.xml",
        "views/certification_view.xml",
        "views/department_info_view.xml",
        "views/designation_info_view.xml",
        "views/division_info_view.xml",
        "views/employee_amedment_view.xml",
        "views/employee_card_view.xml",
        "views/employee_clearance_view.xml",
        "views/employee_iqama_view.xml",
        "views/eos_view.xml",
        "views/eos_leaving_view.xml",
        "views/family_iqama_view.xml",
        "views/hr_ticket_dependent_view.xml",
        "views/hr_ticket_reissue_view.xml",
        "views/insurance_viw.xml",
        "views/res_company_ext_view.xml",
        "views/sponsor_view.xml",
        "views/company_document_view.xml",
        "views/hr_employee_attachments.xml",
        "views/hr_penalty_register_view.xml",
        "views/employee_iqama_document_view.xml",
        "views/menus_view.xml",
        'report/hr_layout.xml',
        "report/employee_dependents_report_template.xml",
        "report/salary_confirmation_report_template.xml",
        "report/employee_info_sheet.xml",
        "report/new_emp_file_form.xml",
        "report/report_action.xml",
    ],
    "qweb": ["static/src/xml/base_template.xml"],
    "installable": True,
    "application": True,
}
