# -*- coding: utf-8 -*-

{
    'name': "Sales Custom",
    'version': "1.0",
    'category': "Sales",
    'author': "Expert Co. Ltd.",
    'website': "http://www.exp-sa.com",
    'summary': "New features for Sales",
    'description': """Contains new features for Sales such as new views""",
    'depends': ['sale_crm', 'crm_custom', 'hr', 'sale_project', 'project_custom'],
    'data': [
        'data/ir_sequence_data.xml',
        'data/mail_data.xml',
        'security/ir.model.access.csv',
        'views/bid_bond_type_view.xml',
        'views/bid_bond_view.xml',
        'wizard/import_sale_data_view.xml',
        'views/sale_order_views.xml',
        'views/proposal_state_view.xml',
        'views/crm_lead_views.xml',
        'views/sale_order_template_views.xml',
        'views/res_config_settings_views.xml',
        'views/res_partner_views.xml',
        'wizard/proposal_common_report_wiz_view.xml',
        'wizard/followup_report_wiz_view.xml',
        'wizard/proposal_inprogress_report_wiz_view.xml',
        'wizard/summary_report_wiz_view.xml',
        'wizard/classification_report_wiz_view.xml',
        'wizard/sector_report_wiz_view.xml',
        'wizard/sector_compare_report_wiz_view.xml',
        'wizard/proposal_status_report_wiz_view.xml',
        'wizard/custom_report_wiz_view.xml',
        'report/followup_report_template.xml',
        'report/proposal_inporgress_report_template.xml',
        'report/classification_report_template.xml',
        'report/sector_report_template.xml',
        'report/proposal_status_report_template.xml',
        'report/custom_report_template.xml',
        'report/bid_opening_view.xml',
        'report/summary_report_template.xml',
    ],
    'installable': True,
    'application': False,
}
