# -*- coding: utf-8 -*-

from . import dependent
from . import certification
from . import insurance
from . import hr_base
from . import application_dependent
from . import category_info
from . import company_document
from . import department_info
from . import designation_info
from . import division_info
from . import employee_amedment
from . import employee_card
from . import employee_clearance
from . import family_iqama
from . import employee_iqama
from . import employee_iqama_renewal
from . import eos_leaving
from . import eos
from . import office
from . import issue_place
from . import res_company_ext
from . import hr_ticket_dependent
from . import hr_ticket_reissue
from . import hr_dependent
from . import hr_sick_leave
from . import hr_employee_attachments
from . import resource
from . import assets_document
